### ISSUE TITLE
Report bug Kodepas Start

### ISSUE THREAD

**Issue by cuzinxyz** [kodestudio/kodepas#11]
**Describe the bug**
Không thể thực thi lệnh "kodepas start"
**To Reproduce**
1. thực thi lệnh : "kodepas start"
2. thông báo lỗi không có lệnh "kodepas", nhưng khi sử dụng "kodepas help" lại có lệnh thực thi.

**Comment by cuzinxyz** [comment]
Vâng, đến thời điểm hiện tại vẫn đang lót dép ngồi hóng ad update ạ ^^

**Comment by quocthinhvo** [comment]
> Vâng, đến thời điểm hiện tại vẫn đang lót dép ngồi hóng ad update ạ ^^

xong rồi bạn nhé.
