### ISSUE TITLE
Khởi tạo project bằng create --cli hoặc qua get kodestudio/project-cli gặp lỗi

### ISSUE THREAD

**Issue by LiquidRekto** [kodestudio/kodepas#26]
**Mô tả**
Khởi tạo project Kode bị gặp lỗi (có thể liên quan đến server)

**Tiến hành lại lỗi**
Các bước tiến hành
1. Vào CMD, dẫn tới thư mục chứa kodepas.exe (nếu chưa cài đặt đường dẫn qua PATH)
2. Nhập lệnh `kodepas create --cli` hoặc `kodepas get kodestudio/project-cli`
3. CMD sẽ báo lỗi sau:

`[Start] Download form Kode Server`
`[Error] Download error`
`[Code ]`
`[Fatal] Kode Getter stop`
`[Start] Unpack`
`[Error] Unpack fail. Error output:`
`[Start] Clear temp`
`[Error] Fail clear`

**Kết quá dự tính**
Lệnh sẽ khởi chạy thành công và người dùng có thể tiến hành làm việc qua project đã tạo

**Thông tin**
- HĐH: Windows 10 Version 1903 (18362.900)

![image](https://user-images.githubusercontent.com/46742676/87440773-8c182d00-c61c-11ea-9a02-1edeb5f2e596.png)

**Comment by quocthinhvo** [comment]
Lỗi do thiếu modul (kpzip và kpunzip) ở máy.

Đã được sửa
